# Generated by Django 4.2.7 on 2023-11-03 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_info',
        ),
    ]
